//esto es explicacion de uso de Try Catch , como no encuentra el metodo sigue con el codigo de la suma de 2 +2 

console.log(1 + 1);

try {
    autenticarUsuario();
    
} catch (error) {
    console.log(error);
}

console.log(2 + 2);